server:
  port: 9991
spring:
  application:
    name: webstore-item-service
  datasource:
    url: jdbc:mysql://localhost/webstore
    username: root
    password: 771003
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15 #15秒不发送就过期
mybatis:
  type-aliases-package: com.webstore.item.pojo
zuul:
  prefix: /api  #网关前缀
  routes:
    webstore-item-service: /item/** #商品微服务的映射路径