server:
  port: 10086
spring:
  application:
    name: webstore-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 10000 # 每隔5秒钟，定期清理无效链接