server:
  port: 9993
spring:
  application:
    name: webstore-detail
  thymeleaf:
    cache: false  #禁用浏览器缓存
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期